version: "3.8"

services:
  frontend:
    build:
      context: ./frontend # Path to the frontend directory
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Expose port for the frontend
    depends_on:
      - backend # Ensure backend is available before frontend starts
    networks:
      - app-network # Define the network for the frontend
    extra_hosts:
      - "backend:host-gateway"

  backend:
    build:
      context: ./backend # Path to the backend directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Expose port for Django backend
    environment:
      - DJANGO_ENV=development # You can customize other environment variables as needed
    networks:
      - app-network # Define the network for the backend

networks:
  app-network: # Define a custom network for the services to communicate
    driver: bridge
