# Generated by Django 5.1.3 on 2024-11-22 13:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dietary_preferences', models.JSONField(blank=True, default=list)),
                ('days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('weight', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grocery_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to='base.groceryplan')),
            ],
        ),
        migrations.AddField(
            model_name='groceryplan',
            name='plan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_plan', to='base.plan'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('frukost', 'Frukost (Breakfast)'), ('lunsj', 'Lunsj (Lunch)'), ('middag', 'Middag (Dinner)')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('time_taken', models.CharField(max_length=100)),
                ('recipe_instructions', models.TextField()),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('applicable_dietary', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='base.plan')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='base.user'),
        ),
    ]
