# Generated by Django 5.1.3 on 2024-11-23 10:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_username_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
