# Generated by Django 5.1.3 on 2024-11-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_plan_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='image',
        ),
    ]
