# Generated by Django 5.1.3 on 2024-11-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_plan_end_date_alter_plan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.IntegerField(),
        ),
    ]
