# Generated by Django 5.1.3 on 2024-11-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_recipe_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='recipe',
            name='frokost',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lunsj',
            field=models.JSONField(default=None),
        ),
        migrations.AddField(
            model_name='recipe',
            name='middag',
            field=models.JSONField(default=None),
        ),
    ]
