# Generated by Django 5.1.3 on 2024-11-23 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_recipe_image_url_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='frokost',
            new_name='frukost',
        ),
    ]
