# Generated by Django 5.1.3 on 2024-11-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_frokost_recipe_frukost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='grocery_plan',
            new_name='groceryPlan',
        ),
        migrations.RenameField(
            model_name='groceryitem',
            old_name='image_url',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='dietary_preferences',
            new_name='dietaryPreferences',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='end_date',
            new_name='endDate',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='start_date',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='applicable_dietary',
            new_name='applicableDietary',
        ),
    ]
