# Generated by Django 5.1.3 on 2024-11-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_grocery_plan_groceryitem_groceryplan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroceryPlan',
            new_name='PlanCheckout',
        ),
    ]
