# Generated by Django 5.1.3 on 2024-11-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_groceryitem_id_alter_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='groceryPlan',
            new_name='planCheckout',
        ),
    ]
